### PR TITLE
Update main.rs

### PR DESCRIPTION
**Pull request by Belbel334**
### changes 
general improvents

### CODE REVIEW

**Comment by GrownPlanet** [comment]
please be more specific than "general improvements"

**Comment by Belbel334** [comment]
i changed some of the numbers in the code because i felt like it

**Comment by GrownPlanet** [comment]
"general improvements" is too subjective; changed numbers because you "felt like it"; visualization is only meant to be a visualization, not a final product.

**Comment by Belbel334** [comment]
Just look at code changes

**Comment by GrownPlanet** [comment]
I did, that was how I decided that they are too subjective

**Pull request closed without merging**
